### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by SokichiFujita** [strapi/strapi-starter-gatsby-blog#32]
Same error is happening as https://github.com/strapi/strapi-starter-gatsby-catalog/issues/22

```
➜  npx create-strapi-starter@latest my-project gatsby-blog
Need to install the following packages:
  create-strapi-starter@latest
Ok to proceed? (y)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
? Choose your installation type Quickstart (recommended)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getPackageInfo (/Users/s/.npm/_npx/9785942591bad2b5/node_modules/create-strapi-starter/utils/fetch-npm-starter.js:19:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getStarterInfo (/Users/s/.npm/_npx/9785942591bad2b5/node_modules/create-strapi-starter/utils/build-starter.js:109:26)
    at async buildStarter (/Users/s/.npm/_npx/9785942591bad2b5/node_modules/create-strapi-starter/utils/build-starter.js:133:7)

```

**Comment by SokichiFujita** [comment]
```
npx create-strapi-starter@3 my-project gatsby-blog
```

will solve this issue like https://github.com/strapi/strapi-starter-gatsby-catalog/issues/22
